### ISSUE TITLE
Page save, save/publish actions hang using youtubefield

### ISSUE THREAD

**Issue by quinnmerio** [edlinklater/silverstripe-youtubefield#11]
Please help?

Has anyone had a similar issue, when saving a page in SilverStripe 3.2 where the actions for the page appear to hang?. The data in the page does get saved to the database, however the wheels on the action buttons never stop spinning. The issue goes away when i comment out the cms formfield.

![screen shot 2016-02-23 at 11 09 34 am](https://cloud.githubusercontent.com/assets/7885598/13261635/544def02-da1e-11e5-90e5-b8ae91a32768.png)

Code is pretty standard:
`private static $db = array(
        'YouTubeVideo' => 'Varchar(20)',
##     );

$fields->addFieldToTab('Root.Main', new YouTubeField('YouTubeVideo', 'YouTube Video'),'Content');
`

**Comment by quinnmerio** [comment]
Perhaps this has to do with it:
![screen shot 2016-02-23 at 11 23 08 am](https://cloud.githubusercontent.com/assets/7885598/13261991/e17eca62-da1f-11e5-9d06-5b739360eb42.png)

**Comment by edlinklater** [comment]
@quinnmerio Sorry for the delay in response here, but I've tested this and haven't been able to reproduce. I suspect it has to do with whatever module is adding the "Publish Page & Blocks" button, as this isn't standard in SS.
