### ISSUE TITLE
Preview works inconsistently

### ISSUE THREAD

**Issue by faloude** [edlinklater/silverstripe-youtubefield#15]
The preview field under the input field seems to work some times, and doesn't appear the other time, using in SS 3.5.1.

At this point I have no clue what's causing it. Will do more tests soon.

**Comment by edlinklater** [comment]
Hi @faloude, did you ever end up figuring this out?

**Comment by faloude** [comment]
I haven't used the mod for a while now. I'll drop a message here at the next install + test.

**Comment by edlinklater** [comment]
Hi @faloude, believe I've now fixed this bug in the 1.1 release, so I'll close the issue. If you see it again, feel free to reopen.
