### ISSUE TITLE
SS4 - Invalid YouTubeID results in Internal Server Error when trying to edit record

### ISSUE THREAD

**Issue by jcop007** [edlinklater/silverstripe-youtubefield#23]
On an SS4 site if you try to edit an record/page which has an invalid YouTubeID on it you get and "Internal Server Error"

[Unknown Error] Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=9uljN1cOPWw&format=json` resulted in a `404 Not Found` response: Not Found
GET /admin/business-listings/TimeZoneOne-TourismOperators-Model-Listings-Product/EditForm/field/TimeZoneOne-TourismOperators-Model-Listings-Product/item/13/edit
Line 113 in /home/loopchicago/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php

This has been addressed by this PR https://github.com/edgarindustries/silverstripe-youtubefield/pull/22

**Comment by edlinklater** [comment]
Fixed by #22
